<?php
session_start();
include "dbconfig.php";
require "component.php";
require_once __DIR__ . '/domPDF_lib/vendor/autoload.php'; // Adjust the path as needed
use Dompdf\Dompdf;

if (isset($_SESSION['username']) && isset($_SESSION['id']) && isset($_SESSION['role']) && $_SESSION['role'] == 'admin'){  
    $session_userid = $_SESSION['username'];

// Perform a SELECT query to fetch data from the database
$sql = "SELECT * FROM settings"; // Replace 'your_table_name' with your actual table name

$result = $con->query($sql);

// Check if there are any rows returned
if ($result->num_rows > 0) {
    // Loop through each row and fetch the data
    while ($row = $result->fetch_assoc()) {
        $appName1 = $row['appName'];
        $appName2 = $row['appName2'];
    }
} else {
    echo "No data found.";
}

function generatePDFFromHTML($html) {
    // require 'vendor/autoload.php';
    // use Dompdf\Dompdf;

    $dompdf = new Dompdf();

    $dompdf->loadHtml($html);

    $dompdf->setPaper('A3', 'portrait');

    // $dompdf->setPaper('A4', 'landscape');

    $dompdf->render();

    return $dompdf->output();
}

$from_date = $_GET['from_date'];
$to_date = $_GET['to_date'];
$categoryID = $_GET['category_id'];
$subcategoryID = $_GET['subcategory_id'];

// Initialize the WHERE clause
$whereClause = "date BETWEEN '$from_date' AND '$to_date'";

// Check if $categoryID and $subcategoryID are not empty
if (!empty($categoryID)) {
    $whereClause .= " AND category_id = $categoryID";
}

if (!empty($subcategoryID)) {
    $whereClause .= " AND subcategory_id = $subcategoryID";
}

// Build the complete query
$query = "SELECT * FROM in_ex WHERE $whereClause";

// $query = "SELECT * FROM in_ex WHERE date BETWEEN '$from_date' AND '$to_date' AND category_id = $categoryID AND subcategory_id = $subcategoryID"; // Modify 'your_table' with the actual table name
$result = mysqli_query($con, $query); // Assuming $connection is your database connection

$html = '
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Income | Expense PDF Report</title>
    <style>
        * {text-align: center;}
        .watermark {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            opacity: 0.5; /* Adjust opacity as needed */
            font-size: 36px;
            color: #999; /* Watermark text color */
            z-index: 9999;
            pointer-events: none; /* Ensure the watermark doesnt interfere with user interactions */
        }
    </style>

</head>
<body>
    <!--div class="watermark">' . $appName2 . '<br/><h6>' . $currentDate . '</h6></div-->
    
    <table border="4" cellpadding="0" cellspacing="0" style="width: 100%;">
        <tr>
            <td colspan="3" style="text-align: center; font-size: 20px;"><b>' . $appName1 . '</b></td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center; font-size: 20px;"><b>Income | Expense Report</b></td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center;">' . $from_date . '&nbsp; - &nbsp;' . $to_date . '</td>
        </tr>
        <tr>
            <td  colspan="3" style="text-align: left;">Generated by : ' . $session_userid . '&nbsp; on &nbsp;' . $currentDate . '&nbsp;/&nbsp;' . $currentTime . '</td>
        </tr>
    </table>
    <br/>
    <table border="1" cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <th>SNo.</th>
            <th>Date</th>
            <!--th>Time</th-->
            <!--th>User</th-->
            <th>Category</th>
            <th>Subcategory</th>
            <th>Remark</th>
            <th>Income</th>
            <th>Expense</th>
        </tr>';
        $in_sum = 0;
        $ex_sum = 0;
        $sno = 1;
        
while ($row = mysqli_fetch_assoc($result)) {
    $inAmt = '';
    $exAmt = '';
    $type = $row['type'];

    if ($type === 'Income') {
        $inAmt = $row['amount'];
        $in_sum += $row['amount'];
    }

    if ($type === 'Expense') {
        $exAmt = $row['amount'];
        $ex_sum += $row['amount'];
    }

    $html .= '
        <tr>
            <td>' . $sno++ . '</td>
            <td style="color: #007DC3;"><b>' . $row['date'] . '</b></td>
            <!--td>' . convertTo12HourFormat($row['time']) . '</td-->
            <!--td>' . $row['username'] . '</td-->
            <td>' . getCategoryName($con, $row['category_id']) . '</td>
            <td>' . getSubCategoryName($con, $row['subcategory_id']) . '</td>
            <td>' . $row['remark'] . '</td>
            <td>' . $inAmt . '</td>
            <td>' . $exAmt . '</td>
        </tr>';
}

$html .= '
        <tr>
            <td colspan="4"></td>
            <td><b>Total :</b></td>
            <td><b>' . $in_sum . '</b></td>
            <td><b>' . $ex_sum . '</b></td>
        </tr>
    </table>  
';

if ($from_date != '' && $from_date != '' && $categoryID === '' && $subcategoryID === ''){

    $profit = $in_sum - $ex_sum;
    $html .='<h1 align="center">Profit : ' . $profit . '</h1>';

}

$html .='
</body>
</html>';

$pdfOutput = generatePDFFromHTML($html);

// Output the PDF
header('Content-Type: application/pdf');
header('Content-Disposition: inline; filename="pdpcabletv-in-ex-report-'.$from_date.'/'.$from_date.'.pdf"');
echo $pdfOutput;

}else{
	header("Location: index.php");
} ?>

